### ISSUE TITLE
Variable types are always Any

### ISSUE THREAD

**Issue by 4brunu** [lvsti/Bridgecraft#4] opened 2018-01-16 13:00 UTC
Hi, I was testing Bridgecraft and noticed variables types are always `Any`.

Here is the header file
```
#import <Foundation/Foundation.h>
@interface TestClass : NSObject
- (NSNumber * _Nonnull)example1FunctionThatReturnsNonnull:(NSString * _Nullable)nullableParameter;
@end
```

Here is the output of the Xcode generated Swift 4 Interface
```
import Foundation
open class TestClass : NSObject {
    open func example1FunctionThatReturnsNonnull(_ nullableParameter: String?) -> NSNumber
}
```

Here is the output of Bridgecraft
```
open class TestClass {
    open func example1FunctionThatReturnsNonnull(_ nullableParameter: Any!) -> Any!
}

```

**Comment by lvsti** [comment] 2018-01-16 19:46
Probably a duplicate of #5, let's discuss it there.

**Closed as completed** 2018-01-18 17:30 UTC
Labels: duplicate
